server:
  port: 17008
knife4j:
  enable: true
  openapi:
    title: 共饮一杯无专属文档
    description: 欲知后事如何，请关注共饮一杯无https://zhanjq.blog.csdn.net/
    email: 111@foxmail.com
    concat: 共饮一杯无
    url: https://zhanjq.blog.csdn.net/
    version: v1.0
    license: Apache 2.0
    terms-of-service-url: https://stackoverflow.com/
    group:
      user:
        group-name: 用户管理
        api-rule: PACKAGE
        api-rule-resources:
          - com.zjq.knife4j.controller.user
      dept:
        group-name: 部门管理
        api-rule: PACKAGE
        api-rule-resources:
          - com.zjq.knife4j.controller.dept
  basic:
    enable: true
    username: admin
    password: admin



