server:
  port: 8888
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cache_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: 192.168.200.146
    port: 6379
    password: kK6/fG8&pN7<
    database: 1
logging:
  level:
    com:
      itheima:
        mapper: debug
        service: info
        controller: info

mybatis:
  mapper-locations: classpath*:**/*Mapper.xml, classpath*:/mybatis-mapper/*.xml

