# field-mapping.properties
唯一编号=id_placeholder
创建时间=create_time
现区域=value001
现医助姓名=value002
脱敏姓名=value003
患者类型=value004
患者首次处方医院所在省份=value005
患者首次处方医院所在城市=value079
患者首次处方医院全称=value006
专家姓名=value007
患者入组编号=value008
入组日期=value009
入组方式=value010
线上入组—电子ICF附件；线下入组—纸质ICF+线下入组单=value011
是否为通过”药师推荐“成功入组=value012
确诊时间=value013
首次处方时间=value014
首次用药时间=value015
患者性别=value016
脱敏电话=value017
是否重复入组=value018
患者出生日期=value019
身高(cm)=value020
体重(kg)=value021
分型=value022
用药=value023
治疗前方案（详细）=value024
治疗后方案=value025
有哪些既往慢性病史=value071
有哪些既往传染病史=value072
是否有过敏史=value026
是否有家族疾病史=value027
既往诺西治疗针数=value028
下一针注射日期=value029
精神状态=value030
哭声|言语=value076
四肢|脊柱|关节=value031
运动功能=value032
进食方式=value033
呼吸功能（是否使用辅助通气）=value034
辅助通气时长（小时）=value035
疲劳感=value044
已做哪些量表评估=value036
评估得分=value037
已添加企微的身份=value038
患者医保所在地=value039
购药渠道=value040
购药详细地址=value041
可参与支付项目=value042
支付备注=value043
患者状态=value045
脱落时间=value046
脱落原因分类=value047
流转时间=value048
流转/承接情况=value049
重启时间=value050
重启原因=value051
详细描述=value052
文档状态=value053
QC质检：ICF签字是否合格/入组单填写是否完整、清晰=value054
QC质检：入组患者登记表信息是否完整合格=value055
质检日期=value056
质检人员=value057
QC：问题发现记录=value058
专员整改反馈=value059
QC质检：问题发现记录=value060