spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    name: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 17003
